package mock

import (
	"context"
	"fmt"
	"strings"

	providercontracts "loreforge/internal/adapters/providers/contracts"
)

type TextProvider struct {
	Model string
}

func (p TextProvider) Name() string { return "mock-text" }

func (p TextProvider) GenerateText(_ context.Context, input providercontracts.TextRequest) (providercontracts.TextResponse, error) {
	content := strings.TrimSpace(input.Prompt)
	if len(content) > 280 {
		content = content[:280]
	}
	return providercontracts.TextResponse{
		Content: fmt.Sprintf("%s\n\n[Generated by MockTextProvider]", content),
		Model:   coalesce(p.Model, "mock-text-v1"),
	}, nil
}

func coalesce(values ...string) string {
	for _, value := range values {
		if value != "" {
			return value
		}
	}
	return ""
}
