package providers

import (
	"context"
	"fmt"
	"strings"

	"loreforge/pkg/contracts"
)

type MockTextProvider struct {
	Model string
}

func (m MockTextProvider) Name() string { return "mock-text" }

func (m MockTextProvider) GenerateText(_ context.Context, input contracts.TextRequest) (contracts.TextResponse, error) {
	content := strings.TrimSpace(input.Prompt)
	if len(content) > 280 {
		content = content[:280]
	}
	return contracts.TextResponse{Content: fmt.Sprintf("%s\n\n[Generated by MockTextProvider]", content), Model: coalesceText(m.Model, "mock-text-v1")}, nil
}

func coalesceText(v ...string) string {
	for _, s := range v {
		if s != "" {
			return s
		}
	}
	return ""
}
